### ISSUE TITLE
Integrate Black, Flake8, & MyPy into yarpc and Travis Config

### ISSUE THREAD

**Issue by Physsix27** [IOMirea/yarpc#23]
- [ ] Integrate Flake8 to `Makefile`
- [ ] Integrate Black to `Makefile`
- [ ] Integrate MyPy to `Makefile`
- [ ] Integrate all thoses targets into Travis CI Pipeline

**Comment by Physsix27** [comment]
I will be working on this issue, please assign to me.

**Comment by Fogapod** [comment]
These tools are already used for testing. Although they are are in pre-commit and there are some issues running pre-commit with Travis.
It would be better to add these to makefile and run them from Travis.
Project uses mypy and black, so add them to list please. Pylint is probably not needed

**Comment by Physsix27** [comment]
Hey @Fogapod, just so I understand the problem that I will solve for this issue, do you want me to add `FLAKE8`, `BLACK` & `MYPY`to the Makefile and also ensure that they get added to Travis as well?
Is this going to be a pre-requisite, meaning if there is a bug with any of them ☝️  Travis should FAIL?

**Comment by Fogapod** [comment]
These linting tools should be included into Makefile.
Travis should use Makefile instead of pre-commit.
This should happen in `script` section. So if something errors, other commands in `script` will still be executed, but build will fail with error and coverage won't be submitted.
